name: Despliegue Continuo jquiroz.net

on:
  push:
    branches:
      - main

  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    name: Despliegue servidor
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY_CURSO }}

    - name: Ejecutar FASTAPI
      run: |
       ssh -o StrictHostKeyChecking=no tscc@jquiroz.net << 'EOF'
          cd /home/tscc/pruebas/calculadora-api
          git pull origin main
          source /home/tscc/pruebas/calculadora-api/.ambiente/bin/activate
          pip install -r requeriments.txt || pip install fastapi uvicorn

          fuser -k 3030/tcp || true
          nohup /home/tscc/pruebas/calculadora-api/.ambiente/bin/uvicorn main:app --host 0.0.0.0 --port 3030 > fastapi.log 2>&1 &
       EOF
